/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.29.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

import { Interface, Contract } from "fuels";
import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import type { ContractAbi, ContractAbiInterface } from "../ContractAbi";

const _abi = {
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "[_; 9]",
      "components": [
        {
          "name": "__array_element",
          "type": 10,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "[_; 9]",
      "components": [
        {
          "name": "__array_element",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "struct Address",
      "components": [
        {
          "name": "value",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "struct Game",
      "components": [
        {
          "name": "game_state",
          "type": 1,
          "typeArguments": null
        },
        {
          "name": "boards_state",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "next_play_position",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "player1",
          "type": 4,
          "typeArguments": null
        },
        {
          "name": "player2",
          "type": 4,
          "typeArguments": null
        },
        {
          "name": "next_player",
          "type": 4,
          "typeArguments": null
        },
        {
          "name": "winner",
          "type": 10,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "struct Join",
      "components": [
        {
          "name": "game_id",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "player",
          "type": 4,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 7,
      "type": "struct Move",
      "components": [
        {
          "name": "game_id",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "board",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "position",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "mark",
          "type": 10,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 8,
      "type": "struct Start",
      "components": [
        {
          "name": "game_id",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "player",
          "type": 4,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "u64",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 10,
      "type": "u8",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "game_id",
          "type": 9,
          "typeArguments": null
        }
      ],
      "name": "join_game",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "board",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "position",
          "type": 10,
          "typeArguments": null
        }
      ],
      "name": "make_play",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "player",
          "type": 4,
          "typeArguments": null
        }
      ],
      "name": "player_state",
      "output": {
        "name": "",
        "type": 9,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "quit_game",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "start_game",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "game_id",
          "type": 9,
          "typeArguments": null
        }
      ],
      "name": "view",
      "output": {
        "name": "",
        "type": 5,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": 0,
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    },
    {
      "logId": 1,
      "loggedType": {
        "name": "",
        "type": 7,
        "typeArguments": []
      }
    },
    {
      "logId": 2,
      "loggedType": {
        "name": "",
        "type": 8,
        "typeArguments": []
      }
    }
  ],
  "messagesTypes": []
}

export class ContractAbi__factory {
  static readonly abi = _abi
  static createInterface(): ContractAbiInterface {
    return new Interface(_abi) as unknown as ContractAbiInterface
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): ContractAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as ContractAbi
  }
}
