/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.29.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type GameInput = { game_state: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], boards_state: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]], next_play_position: BigNumberish, player1: AddressInput, player2: AddressInput, next_player: AddressInput, winner: BigNumberish };
export type GameOutput = { game_state: [number, number, number, number, number, number, number, number, number], boards_state: [[number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number], [number, number, number, number, number, number, number, number, number]], next_play_position: number, player1: AddressOutput, player2: AddressOutput, next_player: AddressOutput, winner: number };
export type JoinInput = { game_id: BigNumberish, player: AddressInput };
export type JoinOutput = { game_id: BN, player: AddressOutput };
export type MoveInput = { game_id: BigNumberish, board: BigNumberish, position: BigNumberish, mark: BigNumberish };
export type MoveOutput = { game_id: BN, board: number, position: number, mark: number };
export type StartInput = { game_id: BigNumberish, player: AddressInput };
export type StartOutput = { game_id: BN, player: AddressOutput };

interface ContractAbiInterface extends Interface {
  functions: {
    join_game: FunctionFragment;
    make_play: FunctionFragment;
    player_state: FunctionFragment;
    quit_game: FunctionFragment;
    start_game: FunctionFragment;
    view: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'join_game', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'make_play', values: [BigNumberish, BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'player_state', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'quit_game', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'start_game', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'view', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'join_game', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'make_play', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'player_state', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'quit_game', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'start_game', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'view', data: BytesLike): DecodedValue;
}

export class ContractAbi extends Contract {
  interface: ContractAbiInterface;
  functions: {
    join_game: InvokeFunction<[game_id: BigNumberish], void>;
    make_play: InvokeFunction<[board: BigNumberish, position: BigNumberish], void>;
    player_state: InvokeFunction<[player: AddressInput], BN>;
    quit_game: InvokeFunction<[], void>;
    start_game: InvokeFunction<[], void>;
    view: InvokeFunction<[game_id: BigNumberish], GameOutput>;
  };
}
